### ISSUE TITLE
Seleccionar libro

### ISSUE THREAD

**Issue by recharged2005** [Colegio-Seminario-Diocesano/solucionario-1104#2]

**Comment by recharged2005** [comment]
Buenos días, ¿en base a que libro vamos a trabajar?

**Comment by Sergio-Colmenares** [comment]
Estan el de Thomas y el de Stewart si?

**Comment by recharged2005** [comment]
Están Thomas, Stewart y Zill

**Comment by Sergio-Colmenares** [comment]
pues por mi el de Thomas, es el que mas he trabajado, pero no se

**Comment by ElTorres26** [comment]
El Thomas sirve más para el calculo, es q el Stewart es más como un precalculo y los unicos ejercicios q hay estan al final y son muy pocos

**Comment by KatherineSHL** [comment]
yo personalmente, pienso que nos basemos mejor en el de Thomas

**Comment by recharged2005** [comment]
Está bien, pues como nadie más habló a mi tambien me parece que el de Thomas está bien

**Comment by ElTorres26** [comment]
Entonces desicion unánime?

**Comment by ElTorres26** [comment]
Q sección vamos a trabajar?

**Comment by mapzt91** [comment]
Lo que dijo Jorge.

**Comment by mapzt91** [comment]
¿Qué sección?

**Comment by recharged2005** [comment]
¿Les parece si lo hacemos de la 3.1?

**Comment by recharged2005** [comment]
En la página 130 del documento

**Comment by recharged2005** [comment]
perdón, la 3.1 está en la 123, la 3.2 si está en la 130

**Comment by ElTorres26** [comment]
Entonces las tareas las organizamos x orden o como le salga a cada uno?

**Comment by KatherineSHL** [comment]
Me parece que la sección que dijo Edil para trabajar la 3.2, esta bien

**Comment by recharged2005** [comment]
pues creo que va a ser muy complicado organizarlos a todos para que sea en orden
